export interface ToolItem {
  id: string;
  name: string;
  category: string;
  description: string;
  iconName: string;
  href: string;
  endpoint: string;
  accept: string;
  multiple: boolean;
  popular?: boolean;
}

export const CATEGORIES = [
  "CONVERT FROM PDF",
  "CONVERT TO PDF",
  "ORGANIZE PDF",
  "OPTIMIZE PDF",
  "EDIT PDF",
  "PDF SECURITY",
  "PDF INTELLIGENCE",
  "INDIAN LANGUAGE DOCUMENTS",
  "VOICE & DOCUMENT",
  "IMAGE TOOLS"
] as const;

export const TOOLS: ToolItem[] = [
  // CONVERT FROM PDF (PDF to whatever)
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    category: "CONVERT FROM PDF",
    description: "Convert PDF documents into editable Word (DOCX) files.",
    iconName: "FileCheck",
    href: "/pdf-to-word",
    endpoint: "pdf-to-word",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    category: "CONVERT FROM PDF",
    description: "Extract PDF pages into crisp JPG image files.",
    iconName: "FileImage",
    href: "/pdf-to-jpg",
    endpoint: "pdf-to-jpg",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    category: "CONVERT FROM PDF",
    description: "Extract PDF tables into editable Excel (XLSX) spreadsheets.",
    iconName: "Sheet",
    href: "/pdf-to-excel",
    endpoint: "pdf-to-excel",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    category: "CONVERT FROM PDF",
    description: "Convert PDF pages into slide deck presentations (PPTX).",
    iconName: "Tv",
    href: "/pdf-to-ppt",
    endpoint: "pdf-to-ppt",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "pdf-to-html",
    name: "PDF to HTML",
    category: "CONVERT FROM PDF",
    description: "Convert PDF documents to clean responsive HTML web pages.",
    iconName: "Code",
    href: "/pdf-to-html",
    endpoint: "pdf-to-html",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "pdf-to-markdown",
    name: "PDF to Markdown",
    category: "CONVERT FROM PDF",
    description: "Convert PDF layout and text into formatted Markdown (.md) documents.",
    iconName: "FileText",
    href: "/pdf-to-markdown",
    endpoint: "pdf-to-markdown",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    category: "CONVERT FROM PDF",
    description: "Convert standard PDF to ISO-compliant archival PDF/A format.",
    iconName: "Archive",
    href: "/pdf-to-pdfa",
    endpoint: "pdf-to-pdfa",
    accept: ".pdf",
    multiple: false,
  },

  // CONVERT TO PDF
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    category: "CONVERT TO PDF",
    description: "Convert DOC and DOCX documents to high-quality PDF files.",
    iconName: "FileText",
    href: "/word-to-pdf",
    endpoint: "word-to-pdf",
    accept: ".doc,.docx",
    multiple: false,
    popular: true,
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    category: "CONVERT TO PDF",
    description: "Convert JPG, PNG, and WebP images to PDF in seconds.",
    iconName: "Image",
    href: "/jpg-to-pdf",
    endpoint: "jpg-to-pdf",
    accept: "image/*",
    multiple: true,
    popular: true,
  },
  {
    id: "ppt-to-pdf",
    name: "PowerPoint to PDF",
    category: "CONVERT TO PDF",
    description: "Convert PPT and PPTX presentations to portable PDF files.",
    iconName: "Presentation",
    href: "/ppt-to-pdf",
    endpoint: "ppt-to-pdf",
    accept: ".ppt,.pptx",
    multiple: false,
    popular: true,
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    category: "CONVERT TO PDF",
    description: "Convert XLS and XLSX spreadsheets to clean PDF documents.",
    iconName: "Table",
    href: "/excel-to-pdf",
    endpoint: "excel-to-pdf",
    accept: ".xls,.xlsx",
    multiple: false,
    popular: true,
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    category: "CONVERT TO PDF",
    description: "Render HTML web pages or code markup directly to PDF.",
    iconName: "Code",
    href: "/html-to-pdf",
    endpoint: "html-to-pdf",
    accept: ".html,.htm",
    multiple: false,
  },

  // ORGANIZE PDF
  {
    id: "merge-pdf",
    name: "Merge PDF",
    category: "ORGANIZE PDF",
    description: "Combine multiple PDF files into one unified document with custom ordering.",
    iconName: "FilePlus",
    href: "/merge-pdf",
    endpoint: "merge-pdf",
    accept: ".pdf",
    multiple: true,
    popular: true,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    category: "ORGANIZE PDF",
    description: "Split a PDF into page ranges, individual pages, or every N pages.",
    iconName: "Scissors",
    href: "/split-pdf",
    endpoint: "split-pdf",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "remove-pages",
    name: "Remove Pages",
    category: "ORGANIZE PDF",
    description: "Select and delete specific pages from your PDF document.",
    iconName: "Trash2",
    href: "/remove-pages",
    endpoint: "remove-pages",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    category: "ORGANIZE PDF",
    description: "Extract page ranges (e.g. 2,5,8-12) into a clean new PDF.",
    iconName: "FileOutput",
    href: "/extract-pages",
    endpoint: "extract-pages",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    category: "ORGANIZE PDF",
    description: "Reorder, rotate, delete, and combine PDF pages visually.",
    iconName: "LayoutGrid",
    href: "/organize-pdf",
    endpoint: "organize-pdf",
    accept: ".pdf",
    multiple: true,
  },
  {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    category: "ORGANIZE PDF",
    description: "Convert photos or scanned document images into a clean PDF.",
    iconName: "Camera",
    href: "/scan-to-pdf",
    endpoint: "scan-to-pdf",
    accept: "image/*",
    multiple: true,
  },

  // OPTIMIZE PDF
  {
    id: "compress-pdf",
    name: "Compress PDF",
    category: "OPTIMIZE PDF",
    description: "Reduce PDF file size while optimizing visual document quality.",
    iconName: "Minimize2",
    href: "/compress-pdf",
    endpoint: "compress-pdf",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "repair-pdf",
    name: "Repair PDF",
    category: "OPTIMIZE PDF",
    description: "Recover and rebuild damaged or corrupted PDF documents.",
    iconName: "Wrench",
    href: "/repair-pdf",
    endpoint: "repair-pdf",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "ocr-pdf",
    name: "OCR PDF",
    category: "OPTIMIZE PDF",
    description: "Extract text from scanned PDFs and create searchable documents.",
    iconName: "ScanText",
    href: "/ocr-pdf",
    endpoint: "ocr-pdf",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },

  // EDIT PDF
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    category: "EDIT PDF",
    description: "Rotate PDF pages 90°, 180°, or 270° degrees clockwise.",
    iconName: "RotateCw",
    href: "/rotate-pdf",
    endpoint: "rotate-pdf",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "add-page-numbers",
    name: "Add Page Numbers",
    category: "EDIT PDF",
    description: "Insert custom page numbers, positions, and formatting into PDF.",
    iconName: "Hash",
    href: "/add-page-numbers",
    endpoint: "add-page-numbers",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "add-watermark",
    name: "Add Watermark",
    category: "EDIT PDF",
    description: "Stamp text or image watermarks over PDF document pages.",
    iconName: "Stamp",
    href: "/add-watermark",
    endpoint: "add-watermark",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "crop-pdf",
    name: "Crop PDF",
    category: "EDIT PDF",
    description: "Trim page margins or select custom crop boundaries on PDF.",
    iconName: "Crop",
    href: "/crop-pdf",
    endpoint: "crop-pdf",
    accept: ".pdf",
    multiple: false,
  },

  // PDF SECURITY
  {
    id: "protect-pdf",
    name: "Protect PDF",
    category: "PDF SECURITY",
    description: "Encrypt PDF with secure AES passwords and permission restrictions.",
    iconName: "Lock",
    href: "/protect-pdf",
    endpoint: "protect-pdf",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    category: "PDF SECURITY",
    description: "Remove PDF passwords and security restrictions cleanly.",
    iconName: "Unlock",
    href: "/unlock-pdf",
    endpoint: "unlock-pdf",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    category: "PDF SECURITY",
    description: "Draw or place digital signatures and initials directly on PDF pages.",
    iconName: "PenTool",
    href: "/sign-pdf",
    endpoint: "sign-pdf",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },
  {
    id: "redact-pdf",
    name: "Redact PDF",
    category: "PDF SECURITY",
    description: "Permanently blackout and purge sensitive text streams from PDF.",
    iconName: "EyeOff",
    href: "/redact-pdf",
    endpoint: "redact-pdf",
    accept: ".pdf",
    multiple: false,
    popular: true,
  },

  // PDF INTELLIGENCE & AI
  {
    id: "compare-pdf",
    name: "Compare PDF",
    category: "PDF INTELLIGENCE",
    description: "Compare two PDF files side-by-side to highlight text differences.",
    iconName: "GitCompare",
    href: "/compare-pdf",
    endpoint: "compare-pdf",
    accept: ".pdf",
    multiple: true,
  },
  {
    id: "ai-pdf-summarizer",
    name: "AI PDF Summarizer",
    category: "PDF INTELLIGENCE",
    description: "Summarize multi-page documents and extract key bullet insights with AI.",
    iconName: "Sparkles",
    href: "/ai-pdf-summarizer",
    endpoint: "ai-pdf-summarizer",
    accept: ".pdf",
    multiple: false,
  },
  {
    id: "translate-pdf",
    name: "Translate PDF",
    category: "PDF INTELLIGENCE",
    description: "Translate PDF content across languages while retaining original layout.",
    iconName: "Globe",
    href: "/translate-pdf",
    endpoint: "translate-pdf",
    accept: ".pdf",
    multiple: false,
  },

  // INDIAN LANGUAGE DOCUMENTS & OCR
  {
    id: "indian-language-documents",
    name: "Indian Language Documents",
    category: "INDIAN LANGUAGE DOCUMENTS",
    description: "Extract OCR text from Hindi, Tamil, Telugu, Kannada, Malayalam, Bengali, Marathi, Gujarati, Punjabi, & Urdu.",
    iconName: "Languages",
    href: "/indian-language-documents",
    endpoint: "indian-language-documents",
    accept: ".pdf,image/*",
    multiple: false,
    popular: true,
  },
  {
    id: "image-to-text",
    name: "Image to Text (OCR)",
    category: "INDIAN LANGUAGE DOCUMENTS",
    description: "Convert photos or scanned document snapshots directly to editable text.",
    iconName: "FileSearch",
    href: "/image-to-text",
    endpoint: "image-to-text",
    accept: "image/*",
    multiple: false,
  },

  // VOICE & DOCUMENT
  {
    id: "voice-to-document",
    name: "Voice to Document",
    category: "VOICE & DOCUMENT",
    description: "Record voice notes with browser microphone to format formal PDF/DOCX reports.",
    iconName: "Mic",
    href: "/voice-to-document",
    endpoint: "voice-to-document",
    accept: "audio/*",
    multiple: false,
    popular: true,
  },

  // IMAGE TOOLS
  {
    id: "resize-image",
    name: "Resize Image",
    category: "IMAGE TOOLS",
    description: "Resize JPG, PNG, and WebP dimensions for web optimization.",
    iconName: "Maximize2",
    href: "/resize-image",
    endpoint: "resize-image",
    accept: "image/*",
    multiple: false,
  },
  {
    id: "crop-image",
    name: "Crop Image",
    category: "IMAGE TOOLS",
    description: "Crop custom aspect ratios and rectangular sections from photos.",
    iconName: "Crop",
    href: "/crop-image",
    endpoint: "crop-image",
    accept: "image/*",
    multiple: false,
  },
  {
    id: "convert-image-format",
    name: "Convert Image Format",
    category: "IMAGE TOOLS",
    description: "Convert between JPG, PNG, WebP, BMP, and TIFF image formats.",
    iconName: "RefreshCw",
    href: "/convert-image-format",
    endpoint: "convert-image-format",
    accept: "image/*",
    multiple: false,
  }
];
